### ISSUE TITLE
command SEARCH illegal in state AUTH

### ISSUE THREAD

**Issue by changchichung** [mjseeley/Gmail-Attachment-Downloader#8]
```
python gmail_downer.py 
Enter your GMail username: cch@abc.com
Enter your password: 
No Recovery file found.
Enter Destination path: /home/chc/Documents/
Items will be saved in /home/chc/Documents/.
Press enter to continue...
Enter sort method [1-5]:
        1. Extension (after download)
        2. Size (after download)
        3. File Type (after download)
        4. Date
        5. Sender
        6. Sender Domain
        7. Test
7
Status: OK
b'cch@abc.com authenticated (Success)'
Traceback (most recent call last):
  File "/home/chc/git/Gmail-Attachment-Downloader/gmail_downer.py", line 170, in <module>
    for msg in generate_mail_messages(user_name, password, resumeFile):
  File "/home/chc/git/Gmail-Attachment-Downloader/gmail_downer.py", line 52, in generate_mail_messages
    typ, data = imap_session.search(None, '(X-GM-RAW "has:attachment")')
  File "/usr/lib/python3.10/imaplib.py", line 734, in search
    typ, dat = self._simple_command(name, *criteria)
  File "/usr/lib/python3.10/imaplib.py", line 1230, in _simple_command
    return self._command_complete(name, self._command(name, *args))
  File "/usr/lib/python3.10/imaplib.py", line 968, in _command
    raise self.error("command %s illegal in state %s, "
imaplib.IMAP4.error: command SEARCH illegal in state AUTH, only allowed in states SELECTED
```

**Comment by mjseeley** [comment]
This option is broken. There was a note in the code for the related function. The label of option "7. Test" was misleading. It was only meant for internal testing of a single function that was intended to sort files based on it's extension as they were being downloaded. It was not meant to to test the anything else.
I'll be removing the option to prevent confusion.

**Comment by changchichung** [comment]
but even with other option , there's still the same error.
